# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: daifend/v1/memory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'daifend/v1/memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61ifend/v1/memory.proto\x12\ndaifend.v1\"\x98\x01\n\x0e\x41nalyzeRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12+\n\nembeddings\x18\x02 \x03(\x0b\x32\x17.daifend.v1.FloatVector\x12\x19\n\x11\x62\x61seline_centroid\x18\x03 \x03(\x02\x12\x14\n\x0ctext_samples\x18\x04 \x03(\t\x12\x15\n\rcollection_id\x18\x05 \x01(\t\"\x1d\n\x0b\x46loatVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"M\n\x15PromptInjectionSignal\x12\x14\n\x0csample_index\x18\x01 \x01(\r\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0f\n\x07reasons\x18\x03 \x03(\t\"\xef\x01\n\x0f\x41nalyzeResponse\x12\x13\n\x0btrust_score\x18\x01 \x01(\x01\x12\x16\n\x0esemantic_drift\x18\x02 \x01(\x01\x12\x1d\n\x15poisoned_cluster_risk\x18\x03 \x01(\x01\x12\x19\n\x11\x61nomalous_indices\x18\x04 \x03(\r\x12\x13\n\x0b\x66ingerprint\x18\x05 \x01(\t\x12\x1b\n\x13recommended_actions\x18\x06 \x03(\t\x12\x43\n\x18prompt_injection_signals\x18\x07 \x03(\x0b\x32!.daifend.v1.PromptInjectionSignal2U\n\x0fMemoryIntegrity\x12\x42\n\x07\x41nalyze\x12\x1a.daifend.v1.AnalyzeRequest\x1a\x1b.daifend.v1.AnalyzeResponseB6Z4github.com/daifend/platform/gen/daifend/v1;daifendv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daifend.v1.memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/daifend/platform/gen/daifend/v1;daifendv1'
  _globals['_ANALYZEREQUEST']._serialized_start=40
  _globals['_ANALYZEREQUEST']._serialized_end=192
  _globals['_FLOATVECTOR']._serialized_start=194
  _globals['_FLOATVECTOR']._serialized_end=223
  _globals['_PROMPTINJECTIONSIGNAL']._serialized_start=225
  _globals['_PROMPTINJECTIONSIGNAL']._serialized_end=302
  _globals['_ANALYZERESPONSE']._serialized_start=305
  _globals['_ANALYZERESPONSE']._serialized_end=544
  _globals['_MEMORYINTEGRITY']._serialized_start=546
  _globals['_MEMORYINTEGRITY']._serialized_end=631
# @@protoc_insertion_point(module_scope)
