apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: daifend
resources:
  - namespace.yaml
  - configmap-env.yaml
  - deployments/api-gateway.yaml
  - deployments/telemetry.yaml
  - services/api-gateway.yaml
  - services/telemetry.yaml
