import type { Edge, Node } from "reactflow";
import type { SystemNodeData } from "@/components/architecture/SystemNode";

export type FlowSurface = "agent" | "memory" | "rag" | "control" | "intel" | "healing" | "soc";

export const architectureNodes: Node<SystemNodeData>[] = [
  {
    id: "apps",
    type: "system",
    position: { x: -360, y: 140 },
    data: {
      kind: "enterprise",
      title: "Enterprise Apps",
      subtitle: "Internal tools, support, CRM, and workflows consuming AI agents.",
      badges: ["prod", "multi-tenant"],
    },
  },
  {
    id: "agents",
    type: "system",
    position: { x: -40, y: 40 },
    data: {
      kind: "agent",
      title: "Autonomous Agents",
      subtitle: "Sessions, permissions, tool usage, inter-agent communication.",
      badges: ["runtime", "sandboxed"],
    },
  },
  {
    id: "rag",
    type: "system",
    position: { x: -40, y: 240 },
    data: {
      kind: "rag",
      title: "RAG Pipeline",
      subtitle: "Ingestion → chunking → retrieval chain validation.",
      badges: ["guardrails"],
    },
  },
  {
    id: "vector",
    type: "system",
    position: { x: 260, y: 240 },
    data: {
      kind: "vector",
      title: "Vector Database",
      subtitle: "Namespaces, embeddings, memory lineage and rollback.",
      badges: ["pinecone", "weaviate"],
    },
  },
  {
    id: "llm",
    type: "system",
    position: { x: 260, y: 40 },
    data: {
      kind: "llm",
      title: "LLM Providers",
      subtitle: "OpenAI / Azure OpenAI / Bedrock / Anthropic.",
      badges: ["models", "routing"],
    },
  },
  {
    id: "daifend",
    type: "system",
    position: { x: 260, y: 140 },
    data: {
      kind: "daifend",
      title: "Daifend Control Plane",
      subtitle: "Memory integrity, runtime enforcement, telemetry, response.",
      badges: ["policy", "audit"],
    },
  },
  {
    id: "intel",
    type: "system",
    position: { x: 560, y: 40 },
    data: {
      kind: "intel",
      title: "AI Threat Intelligence",
      subtitle: "Signatures, synthetic identity signals, model manipulation.",
      badges: ["signatures"],
    },
  },
  {
    id: "healing",
    type: "system",
    position: { x: 560, y: 240 },
    data: {
      kind: "healing",
      title: "Self-Healing Engine",
      subtitle: "Isolation, rollback orchestration, trust restoration workflows.",
      badges: ["autonomous"],
    },
  },
  {
    id: "siem",
    type: "system",
    position: { x: 860, y: 140 },
    data: {
      kind: "siem",
      title: "SOC Integrations",
      subtitle: "CrowdStrike / Sentinel / SIEM pipelines.",
      badges: ["export", "alerts"],
    },
  },
];

export const architectureEdges: Array<Edge & { data?: { surface?: FlowSurface } }> = [
  {
    id: "apps->agents",
    source: "apps",
    target: "agents",
    animated: true,
    className: "df-edge df-edge--primary",
    label: "requests",
    data: { surface: "agent" },
  },
  {
    id: "apps->rag",
    source: "apps",
    target: "rag",
    animated: true,
    className: "df-edge df-edge--muted",
    label: "documents",
    data: { surface: "rag" },
  },
  {
    id: "agents->llm",
    source: "agents",
    target: "llm",
    animated: true,
    className: "df-edge df-edge--primary",
    label: "prompts",
    data: { surface: "agent" },
  },
  {
    id: "rag->vector",
    source: "rag",
    target: "vector",
    animated: true,
    className: "df-edge df-edge--muted",
    label: "embeddings",
    data: { surface: "memory" },
  },
  {
    id: "agents->vector",
    source: "agents",
    target: "vector",
    animated: true,
    className: "df-edge df-edge--muted",
    label: "retrieval",
    data: { surface: "memory" },
  },
  {
    id: "daifend->agents",
    source: "daifend",
    target: "agents",
    animated: true,
    className: "df-edge df-edge--control",
    label: "policies",
    data: { surface: "control" },
  },
  {
    id: "daifend->rag",
    source: "daifend",
    target: "rag",
    animated: true,
    className: "df-edge df-edge--control",
    label: "validation",
    data: { surface: "control" },
  },
  {
    id: "daifend->vector",
    source: "daifend",
    target: "vector",
    animated: true,
    className: "df-edge df-edge--control",
    label: "integrity",
    data: { surface: "control" },
  },
  {
    id: "intel->daifend",
    source: "intel",
    target: "daifend",
    animated: true,
    className: "df-edge df-edge--primary",
    label: "signatures",
    data: { surface: "intel" },
  },
  {
    id: "daifend->healing",
    source: "daifend",
    target: "healing",
    animated: true,
    className: "df-edge df-edge--primary",
    label: "response",
    data: { surface: "healing" },
  },
  {
    id: "healing->vector",
    source: "healing",
    target: "vector",
    animated: true,
    className: "df-edge df-edge--heal",
    label: "rollback",
    data: { surface: "healing" },
  },
  {
    id: "daifend->siem",
    source: "daifend",
    target: "siem",
    animated: true,
    className: "df-edge df-edge--muted",
    label: "alerts",
    data: { surface: "soc" },
  },
];

